require:
  - rubocop-performance
  - rubocop-rspec

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - webmention-verification.gemspec
    - spec/**/*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
