require:
  - rubocop-performance
  - rubocop-rspec

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
